spring:
  datasource:
    url: jdbc:h2:mem:sms
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

management:
  server:
    port: 8001

server:
  port: 8000

app:
  config:
    test-prop: "testValue"